# Generated by Django 6.0.8 on 2026-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('original_video', models.FileField(upload_to='videos/original/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
