# Generated by Django 6.0.8 on 2026-08-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_ready',
            field=models.BooleanField(default=False),
        ),
    ]
